### PR TITLE
Further edits on the CellRanger-like emptyDrops

### PR DESCRIPTION
**Pull request by LTLA**
Refactors the code from #64 to use a cleaner closure-based structure.

### CODE REVIEW

**Comment by DongzeHE** [comment]
Hi @LTLA,

I read STARsolo code again line by line, and I am sure that the version in my PR exactly follows STARsolo's code. I know that's not how EmptyDrops generally works, but that's what STARsolo has. 

I want to explain STARsolo's `emptyDrops_CR` pipeline explicitly, hope I can express why I wrote code in that way.

let's call the cell ranger version **CR** and DropletUtils version **DU**. Suppose barcodes are ordered descendingly by UMI count (`total` in EmptyDrops). The sorted UMI count vector is `totals`, each value is the `total` UMI count a cell has.

## [1. Simple Filtering](https://github.com/alexdobin/STAR/blob/2eb750b45549f6b30a3a01f3b9e166e2de72a57d/source/SoloFeature_cellFiltering.cpp#L39)

Three parameters are used in this process (=> means the name in my code)
- `nExpectedCells` =3000 => `expected`
- `maxPercentile` = 0.99 => `max.percentile`
- `maxMinRatio` = 10 => `maxMinRatio`

This process aims to get an integer `nCellsSimple`, which says the top `nCellSimple` barcodes will be regarded as real cells without future selection (same as `retain` in EmptyDrops` function`). 

### Steps:
1. Define `maxind` = `nExpectedCells` * (1.0 - `maxPercentile`). 
2. Define `nUMImax` = `totals`[maxind].
3. Define `nUMImin` = round(nUMImax/maxMinRatio). This is the minimum `total` a `nCellsSimple` cell needs to have. 
4. Define `nExpectedCells` as sum(`totals` > `nUMImin`)


## [2. SGT](https://github.com/alexdobin/STAR/blob/2eb750b45549f6b30a3a01f3b9e166e2de72a57d/source/SoloFeature_emptyDrops_CR.cpp#L46)

Two parameters are used to define the cells used in SGT.
- `indMax` => `ind.max`
- `indMin` => `ind.min`

Those two parameters are used to define the cells used in SGT, the default value of `indMax` = 90,000, that of `indMin` = 45,000. This means SGT is performed only using cells whose `total` rank is between 45,000 and 90,000.

## [3. Select candidate cells](https://github.com/alexdobin/STAR/blob/2eb750b45549f6b30a3a01f3b9e166e2de72a57d/source/SoloFeature_emptyDrops_CR.cpp#L116)

Following parameters are used:
- `candMaxN` => `can.max.n`
- `nCellsSimple` => `n.cells.simple`
- `umiMinFracMedian` => `umi.min.frac.median`

Following parameters are calculated:
- `iCandFirst` = `nCellsSimple`. It means that the candidate pool starts right after the simple filtering cells.
- `iCandLast` = `iCandFirst` + `candMaxN`. By default, `candMaxN` = 20,000, which means the candidate pool can have at most 20,000 barcodes.  If the `totals`[`iCandLast`] < `umiMinFracMedian` * `totals`[n.cells.simple/2], `iCandLast` will be updated accordingly.

## [4. compute FDR for candidate cells](https://github.com/alexdobin/STAR/blob/2eb750b45549f6b30a3a01f3b9e166e2de72a57d/source/SoloFeature_emptyDrops_CR.cpp#L134)

For barcodes in the **candidate pool** from step 3, the observed probability will be computed. Subsequently, the p-value and FDR will be calculated for each barcode in the candidate pool. According to the FDR threshold (0.01 by default), candidate barcodes whose FDR is less than the threshold will be regarded as real cells, together with `n.cells.simple` cells.

So in cellranger branch, I notice that you set 
```R
        max.rank <- min(ind.max + 1, length(totals), i.cand.last)
```

and then 

```R
        ambient[o[ind.min:max.rank]] <- TRUE
```

Here `ind.max` is the parameter defining barcodes used in SGT (default 90,000), and `i.cand.last` is the parameter used to set the candidate pool (~27,000), so `max.rank` will always be `ind.max`.

## Mapping back to `DropletUtils` code:

In function `test_empty_drops`, `ambient` should be defined by `ind.min` and `ind.max` (by default, 45,000 and 90,000). Then, `keep`

**Comment by LTLA** [comment]
The main point of my refactor was architectural - to make the Cellranger code use closures. I don't have much opinion on the actual calculation itself; I was hoping that you would fix any regressions.

Why closures? This restricts the influence of the CR code on the original `emptyDrops` code to the ambient calculation, without requiring additional arguments to the various `emptyDrops` internal functions. As a result, any fixes that you need to apply should be limited in scope to the `ambfun` definition in the new `emptyDropsCellRanger.R`.

**Comment by LTLA** [comment]
Only clean-ups to the documentation required. I have done a bit of it but don't really have time to finish it. Note the general "1-line, 1 sentence" rule, plus some grammatical fixes. 

Also eliminated the `is.cell` column. Users can just call that themselves with an FDR of their choosing, this should not be the responsibility of the function. On that note, the `fdr=` argument can also be removed.

**Comment by allyhawkins** [comment]
Hi @LTLA and @DongzeHE, thanks so much for adding this function in! We have been testing it out in combination with Alevin-fry and when trying to actually use the package at the cellranger branch,  I noticed an error in the ambient function. It appears that the `ambfun` within `emptyDropsCellRanger()` takes as input a variable named `mat`, but that variable is never actually used in the function. Instead it appears to require the variable `m` within the function. I assumed that those variables should be the same name in order for the function to be correct, otherwise it appears that the function doesn't work.

**Comment by LTLA** [comment]
@allyhawkins where are you seeing  this?

**Comment by allyhawkins** [comment]
@LTLA it appears to have been fixed in the more recent commits.

**Comment by LTLA** [comment]
Thanks all - it is done. Should make its way to BioC-devel over the next day or so.

**Pull request merged**
