### PR TITLE
Store "sample" as factor (memory efficiency).

### PR DESCRIPTION
**Pull request by kevinrue**
The only relevant change is `Sample = factor(rep(run, length(cell.names)), unique(samples)),`.
The rest is RStudio doing it's automatic whitespace cleanup.

### CODE REVIEW

**Comment by LTLA** [comment]
Is this really more memory efficient? Keep in mind that R stores character strings as a pointer to a global string cache (see https://cran.r-project.org/doc/manuals/r-release/R-ints.html#The-CHARSXP-cache), so it's not really storing a separate string for each instance, despite what `object.size` might say.

**Comment by LTLA** [comment]
And in any case, if you're worried about memory efficiency, you should be using `CharacterRle`s.

**Comment by kevinrue** [comment]
Ah right. Perhaps not the most memory efficient yet, but I mainly wanted to point to the fact that this Sample column is storing as character something highly repetitive. I didn't know about the global string cache and I forgot about the `CharacterRle`s for a moment there.
I've updated the PR, but feel free to close it without merging if it's not relevant/desirable in any way.

**Comment by kevinrue** [comment]
So far I had only tried with the small example from `write10xCounts` which creates 10 dummy cells. In this case the `Rle` is actually bigger than the `character` (1352 bytes vs 352 bytes).

However, when I push that dummy example to 1000 cells, the `Rle` stays at 1352 bytes (still a single character with a single integer run length), while the `character` shoots up at `8224 bytes`.

Still, I get your point that it takes a fairly large number of cells to make the memory efficiency _really_ worth it.

**Comment by LTLA** [comment]
To be sure: we are talking about the _serialized_ file from running `saveRDS`, right? As I said above, `object.size` cannot be trusted as it probably doesn't acknowledge the string cache.

**Comment by LTLA** [comment]
Ah, actually, `object.size` is fairly smart:

```r
object.size(strrep("#", rep(1000, 10000)))
## 81104 bytes
object.size(strrep("#", rep(100, 10000)))
## 80224 bytes
object.size(strrep("#", rep(10, 10000)))
## 80112 bytes
```

So you can see that each element just requires 8 bytes, with a fixed overhead from the cache.

**Comment by LTLA** [comment]
All in all, I think using an `Rle` is probably overkill. In particular, it's unnecessarily confusing for the savings it's going to offer, especially if `sample` is used elsewhere. Admittedly, I've made similar decisions before (see the `fastMNN` output), which was probably over-engineering with the benefit of hindsight.

**Comment by kevinrue** [comment]
Just to conclude

> To be sure: we are talking about the _serialized_ file from running `saveRDS`, right? As I said above, `object.size` cannot be trusted as it probably doesn't acknowledge the string cache.

Actually, I've just checked the the _serialized_ file from running `saveRDS`. There's barely any difference there, for 1,000 cells:

- character: 114.8KB
- Rle: 114.3KB

I agree with the overkill thought. Nevermind then!

**Pull request closed without merging**
